{% set name = "kwarray" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kwarray-{{ version }}.tar.gz
  sha256: c7015c20330239ba48260ffab53713a8374b6ac2807e0a42f526c8577cd473f0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=41.0.1
  run:
    - numpy
    - packaging >=21.3
    - python >=3.8
    - ubelt >=1.2.3

test:
  imports:
    - kwarray
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.kitware.com/computer-vision/kwarray
  summary: The kwarray module
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Erotemic
    - vicentebolea
